=== api-evangelist/avalara/json-schema/avalara-accountregistration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/AccountRegistration",
  "title": "AccountRegistration",
  "type": "object",
  "required": [
    "companyName",
    "email"
  ],
  "properties": {
    "companyName": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "phoneNumber": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      }
    },
    "partnerCode": {
      "type": "string"
    }
  }
}

=== api-evangelist/avalara/examples/business-account-registration-example.json
{
  "companyName": "Sample Name",
  "firstName": "Sample Name",
  "lastName": "Sample Name",
  "email": "user@example.com",
  "phoneNumber": "sample-value",
  "address": {
    "line1": "sample-value",
    "city": "sample-value",
    "region": "sample-value",
    "postalCode": "US",
    "country": "sample-value"
  },
  "partnerCode": "US"
}
