=== api-evangelist/avalara/json-schema/avalara-certificatemodel-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/CertificateModel",
  "title": "CertificateModel",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "companyId": {
      "type": "integer"
    },
    "signedDate": {
      "type": "string",
      "format": "date"
    },
    "expirationDate": {
      "type": "string",
      "format": "date"
    },
    "exemptionNumber": {
      "type": "string"
    },
    "exemptPercentage": {
      "type": "number",
      "format": "double"
    },
    "exemptionReason": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "status": {
      "type": "string"
    },
    "createdDate": {
      "type": "string",
      "format": "date-time"
    },
    "modifiedDate": {
      "type": "string",
      "format": "date-time"
    }
  }
}

=== api-evangelist/avalara/examples/avatax-rest-certificate-model-example.json
{
  "id": 42,
  "companyId": 42,
  "signedDate": "2025-04-15",
  "expirationDate": "2025-04-15",
  "exemptionNumber": "sample-value",
  "exemptPercentage": 100.0,
  "exemptionReason": {
    "id": 42,
    "name": "Sample Name"
  },
  "status": "Active",
  "createdDate": "2025-04-15T14:30:00Z",
  "modifiedDate": "2025-04-15T14:30:00Z"
}
