=== api-evangelist/avalara/json-schema/avalara-payercompany-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/PayerCompany",
  "title": "PayerCompany",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "ein": {
      "type": "string",
      "description": "Employer Identification Number"
    },
    "address": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        }
      }
    },
    "contactName": {
      "type": "string"
    },
    "contactPhone": {
      "type": "string"
    },
    "contactEmail": {
      "type": "string",
      "format": "email"
    }
  }
}

=== api-evangelist/avalara/examples/1099-w9-payer-company-example.json
{
  "id": "12345",
  "name": "Sample Name",
  "ein": "sample-value",
  "address": {
    "line1": "sample-value",
    "city": "sample-value",
    "state": "sample-value",
    "postalCode": "US"
  },
  "contactName": "Sample Name",
  "contactPhone": "sample-value",
  "contactEmail": "user@example.com"
}
