=== api-evangelist/avalara/json-schema/avalara-sharedcompany-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/SharedCompany",
  "title": "SharedCompany",
  "type": "object",
  "properties": {
    "companyId": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    },
    "companyCode": {
      "type": "string"
    },
    "taxPayerId": {
      "type": "string",
      "description": "Tax identification number"
    },
    "address": {
      "type": "object",
      "properties": {
        "line1": {
          "type": "string"
        },
        "line2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      }
    },
    "phoneNumber": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "isActive": {
      "type": "boolean"
    },
    "createdDate": {
      "type": "string",
      "format": "date-time"
    },
    "modifiedDate": {
      "type": "string",
      "format": "date-time"
    }
  }
}

=== api-evangelist/avalara/examples/shared-company-service-shared-company-example.json
{
  "companyId": "12345",
  "companyName": "Sample Name",
  "companyCode": "US",
  "taxPayerId": "12345",
  "address": {
    "line1": "sample-value",
    "line2": "sample-value",
    "city": "sample-value",
    "region": "sample-value",
    "postalCode": "US"
  },
  "phoneNumber": "sample-value",
  "email": "user@example.com",
  "isActive": true,
  "createdDate": "2025-04-15T14:30:00Z",
  "modifiedDate": "2025-04-15T14:30:00Z"
}
